apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard-deployment
  labels:
    app: focalboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      containers:
      - name: focalboard
        image: mattermost/focalboard
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: focalboard-service
  labels:
    app: focalboard
  annotations:
    dev.okteto.com/auto-ingress: "true"  
spec:
  type: LoadBalancer
  selector:
    app: focalboard
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
